### ISSUE TITLE
Incorrect return type for methods returning lists

### ISSUE THREAD

**Issue by a3kov** [rockneurotiko/telegram_api_json#27]
Methods that return lists have slightly incorrect return type in JSON, leading to incorrectly generated typespecs in `ex_gram` - in the typespec array (list) of values is converted to single value of the same type. I will admit, whether it's a bug of this project is debatable, because it's `ex_gram` which is interpreting the JSON, but I think the treatment of return types should in general follow the treatment of function arguments (and in `ex_gram` same `type_to_spec()` helper function is used), so we can classify it as a bug of `telegram_api_json`

First, if you look at `getMyCommands`, it's return type is the following:
```json
[
  "array",
  [
    "BotCommand"
  ]
]
```
But then let's compare it to `setMyCommands` param type:
```json
[
  [
    "array",
    [
      "BotCommand"
    ]
  ]
]
```
That extra set of brackets makes the difference, because simple `["array", [model]]` in the extractor is converted to `[model]` which is not what we want - it's a union type, not an array of values. With the extra set of brackets it should be properly processed to `[{:array, model}]` in the extractor. I hope my analysis is correct..

**Comment by rockneurotiko** [comment]
Nice analysis! The bug is definitely here and it's exactly as you said, the first array defines a union type, and we want the list.

I'll take a look 👀
