### ISSUE TITLE
Incorrect generated params for methods with empty request body

### ISSUE THREAD

**Issue by a3kov** [rockneurotiko/telegram_api_json#29]
Methods with empty request body seem to have some other method's params (send message ?)
For example: logOut, close

**Comment by rockneurotiko** [comment]
Oh, totally, I have to manually exclude the methods with zero parameters. I'm going to add `logOut` and `close`, let me know if you detect others

**Comment by a3kov** [comment]
I think its some other condition, not just empty params. Some methods have empty params and are correctly parsed, e.g. "getWebhookInfo"

**Comment by a3kov** [comment]
ah lol
